name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.7'

    - name: Build for Apple Silicon
      run: swift build -c release --arch arm64

    - name: Build for Intel
      run: swift build -c release --arch x86_64

    - name: Create universal binary
      run: |
        mkdir -p build
        cp .build/arm64-apple-macosx/release/agenda build/agenda-arm64
        cp .build/x86_64-apple-macosx/release/agenda build/agenda-x86_64
        lipo -create build/agenda-arm64 build/agenda-x86_64 -output build/agenda-universal

    - name: Prepare release artifacts
      run: |
        mkdir -p releases
        cp build/agenda-arm64 releases/agenda-${{ github.ref_name }}-macos-arm64
        cp build/agenda-x86_64 releases/agenda-${{ github.ref_name }}-macos-x86_64
        cp build/agenda-universal releases/agenda-${{ github.ref_name }}-macos-universal
        chmod +x releases/*

    - name: Generate checksums
      run: |
        cd releases
        shasum -a 256 * > checksums.txt

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          releases/agenda-${{ github.ref_name }}-macos-arm64
          releases/agenda-${{ github.ref_name }}-macos-x86_64
          releases/agenda-${{ github.ref_name }}-macos-universal
          releases/checksums.txt
        body: |
          ## Installation

          ### macOS Universal (Recommended)
          ```bash
          curl -L https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/agenda-${{ github.ref_name }}-macos-universal -o agenda
          chmod +x agenda
          sudo mv agenda /usr/local/bin/
          ```

          ### Architecture-specific downloads
          - **Apple Silicon (M1/M2/M3)**: `agenda-${{ github.ref_name }}-macos-arm64`
          - **Intel**: `agenda-${{ github.ref_name }}-macos-x86_64`
          - **Universal**: `agenda-${{ github.ref_name }}-macos-universal` (works on both)

          ## Verify checksums
          Download `checksums.txt` and verify with:
          ```bash
          shasum -a 256 -c checksums.txt
          ```
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
